"""add appointments

Revision ID: 06b458b3bd49
Revises: 39b27f11296c
Create Date: 2026-09-04 01:29:43.573079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b458b3bd49'
down_revision: Union[str, Sequence[str], None] = '39b27f11296c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('cal_booking_uid', sa.String(length=255), nullable=True),
    sa.Column('event_type_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attendee_name', sa.String(length=255), nullable=False),
    sa.Column('attendee_email', sa.String(length=255), nullable=True),
    sa.Column('attendee_phone', sa.String(length=50), nullable=True),
    sa.Column('time_zone', sa.String(length=100), nullable=False),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cal_booking_uid')
    )
    op.create_index('ix_appointment_tenant_start', 'appointments', ['tenant_id', 'start_at'], unique=False)
    op.create_index('ix_appointment_tenant_status', 'appointments', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index('ix_appointment_tenant_status', table_name='appointments')
    op.drop_index('ix_appointment_tenant_start', table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
