"""add lead id to conversations

Revision ID: 1250def90d1a
Revises: 68490f231480
Create Date: 2026-09-28 16:49:40.669386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1250def90d1a'
down_revision: Union[str, Sequence[str], None] = '68490f231480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'lead_id')
    # ### end Alembic commands ###
