"""add tenant phone and email

Revision ID: 15cb934546bc
Revises: 5f125032c2b9
Create Date: 2026-09-05 19:53:11.250489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cb934546bc'
down_revision: Union[str, Sequence[str], None] = '5f125032c2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'phone')
    # ### end Alembic commands ###
