"""add appointments table

Revision ID: 5ec5929829db
Revises: 06b458b3bd49
Create Date: 2026-09-04 23:20:58.692950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ec5929829db'
down_revision: Union[str, Sequence[str], None] = '06b458b3bd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('cal_booking_id', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('cal_event_type_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('appointments', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('appointments', sa.Column('customer_name', sa.String(length=255), nullable=False))
    op.add_column('appointments', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('customer_phone', sa.String(length=50), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('appointments_cal_booking_uid_key'), 'appointments', type_='unique')
    op.drop_index(op.f('ix_appointment_tenant_start'), table_name='appointments')
    op.drop_index(op.f('ix_appointment_tenant_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.create_index('ix_appointments_cal_booking', 'appointments', ['cal_booking_id'], unique=False)
    op.create_index('ix_appointments_tenant_start', 'appointments', ['tenant_id', 'start_time'], unique=False)
    op.create_index('ix_appointments_tenant_status', 'appointments', ['tenant_id', 'status'], unique=False)
    op.drop_constraint(op.f('appointments_customer_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_tenant_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_lead_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'customers', ['customer_id'], ['id'])
    op.drop_column('appointments', 'end_at')
    op.drop_column('appointments', 'lead_id')
    op.drop_column('appointments', 'attendee_name')
    op.drop_column('appointments', 'start_at')
    op.drop_column('appointments', 'title')
    op.drop_column('appointments', 'cal_booking_uid')
    op.drop_column('appointments', 'meeting_url')
    op.drop_column('appointments', 'event_type_id')
    op.drop_column('appointments', 'attendee_email')
    op.drop_column('appointments', 'attendee_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('attendee_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('attendee_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('event_type_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('meeting_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('cal_booking_uid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('attendee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_lead_id_fkey'), 'appointments', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('appointments_tenant_id_fkey'), 'appointments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('appointments_customer_id_fkey'), 'appointments', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_appointments_tenant_status', table_name='appointments')
    op.drop_index('ix_appointments_tenant_start', table_name='appointments')
    op.drop_index('ix_appointments_cal_booking', table_name='appointments')
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_appointment_tenant_status'), 'appointments', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_appointment_tenant_start'), 'appointments', ['tenant_id', 'start_at'], unique=False)
    op.create_unique_constraint(op.f('appointments_cal_booking_uid_key'), 'appointments', ['cal_booking_uid'], postgresql_nulls_not_distinct=False)
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'customer_phone')
    op.drop_column('appointments', 'customer_email')
    op.drop_column('appointments', 'customer_name')
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    op.drop_column('appointments', 'cal_event_type_id')
    op.drop_column('appointments', 'cal_booking_id')
    op.drop_column('appointments', 'conversation_id')
    # ### end Alembic commands ###
