"""fix customer lead appointment relationships

Revision ID: 5f125032c2b9
Revises: 81afd4fb595c
Create Date: 2026-09-05 19:43:34.464826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f125032c2b9'
down_revision: Union[str, Sequence[str], None] = '81afd4fb595c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_cal_booking'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_tenant_start'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_tenant_status'), table_name='appointments')
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('conversations', 'channel',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_tenant_customer'), table_name='conversations')
    op.drop_constraint(op.f('conversations_tenant_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_customer_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'tenants', ['tenant_id'], ['id'])
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_customer_tenant_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_constraint(op.f('uq_customer_tenant_phone'), 'customers', type_='unique')
    op.drop_constraint(op.f('customers_tenant_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'tenants', ['tenant_id'], ['id'])
    op.add_column('leads', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'customers', ['customer_id'], ['id'])
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_message_conversation_created'), table_name='messages')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_message_conversation_created'), 'messages', ['conversation_id', 'created_at'], unique=False)
    op.alter_column('messages', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_column('leads', 'customer_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_tenant_id_fkey'), 'customers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_customer_tenant_phone'), 'customers', ['tenant_id', 'phone'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_customer_tenant_email'), 'customers', ['tenant_id', 'email'], unique=False)
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('customers', 'updated_at')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_customer_id_fkey'), 'conversations', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('conversations_tenant_id_fkey'), 'conversations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversation_tenant_customer'), 'conversations', ['tenant_id', 'customer_id'], unique=False)
    op.alter_column('conversations', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('conversations', 'channel',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('conversations', 'updated_at')
    op.create_index(op.f('ix_appointments_tenant_status'), 'appointments', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_start'), 'appointments', ['tenant_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_appointments_cal_booking'), 'appointments', ['cal_booking_id'], unique=False)
    # ### end Alembic commands ###
