"""add cal booking uid

Revision ID: 5f9f7951725c
Revises: ca84f3dd5aea
Create Date: 2026-09-29 15:20:00.944227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9f7951725c'
down_revision: Union[str, Sequence[str], None] = 'ca84f3dd5aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cal_booking_uid', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'appointments', ['cal_booking_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='unique')
    op.drop_column('appointments', 'cal_booking_uid')
    # ### end Alembic commands ###
