"""add unique constraint to reviews

Revision ID: 5fa881bba14b
Revises: 9dec271164db
Create Date: 2026-09-11 01:04:23.515479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa881bba14b'
down_revision: Union[str, Sequence[str], None] = '9dec271164db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reviews_tenant_appointment', 'reviews', ['tenant_id', 'appointment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reviews_tenant_appointment', 'reviews', type_='unique')
    # ### end Alembic commands ###
