"""add vapi call id to conversations

Revision ID: 68490f231480
Revises: 5990749c5c20
Create Date: 2026-09-28 00:32:28.671900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68490f231480'
down_revision: Union[str, Sequence[str], None] = '5990749c5c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('vapi_call_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_conversations_vapi_call_id'), 'conversations', ['vapi_call_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_vapi_call_id'), table_name='conversations')
    op.drop_column('conversations', 'vapi_call_id')
    # ### end Alembic commands ###
