"""unique tenant knowledge source

Revision ID: 77ef56092a3b
Revises: ca3c76c2de5a
Create Date: 2026-09-17 19:49:41.729503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ef56092a3b'
down_revision: Union[str, Sequence[str], None] = 'ca3c76c2de5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_knowledge_documents_tenant_source', 'knowledge_documents', ['tenant_id', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_knowledge_documents_tenant_source', 'knowledge_documents', type_='unique')
    # ### end Alembic commands ###
