"""add lead score

Revision ID: 81afd4fb595c
Revises: 5ec5929829db
Create Date: 2026-09-05 18:53:51.102974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81afd4fb595c'
down_revision: Union[str, Sequence[str], None] = '5ec5929829db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_score', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_lead_tenant_phone'), table_name='leads')
    op.drop_index(op.f('ix_lead_tenant_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_constraint(op.f('leads_tenant_id_fkey'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('leads_customer_id_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('leads', 'source')
    op.drop_column('leads', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_customer_id_fkey'), 'leads', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('leads_tenant_id_fkey'), 'leads', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lead_tenant_status'), 'leads', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_lead_tenant_phone'), 'leads', ['tenant_id', 'phone'], unique=False)
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('leads', 'updated_at')
    op.drop_column('leads', 'lead_score')
    # ### end Alembic commands ###
