"""add lead follow up fields

Revision ID: 94be820c825f
Revises: d99c966c1883
Create Date: 2026-09-09 23:12:27.359886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94be820c825f'
down_revision: Union[str, Sequence[str], None] = 'd99c966c1883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('follow_up_count', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('follow_up_status', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_leads_next_follow_up_at'), 'leads', ['next_follow_up_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_next_follow_up_at'), table_name='leads')
    op.drop_column('leads', 'follow_up_status')
    op.drop_column('leads', 'follow_up_count')
    op.drop_column('leads', 'last_contacted_at')
    op.drop_column('leads', 'next_follow_up_at')
    # ### end Alembic commands ###
