"""add review request schedule

Revision ID: b88bf2dbf3ed
Revises: 5fa881bba14b
Create Date: 2026-09-11 02:12:25.333722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88bf2dbf3ed'
down_revision: Union[str, Sequence[str], None] = '5fa881bba14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_request_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_reviews_review_request_at'), 'reviews', ['review_request_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_review_request_at'), table_name='reviews')
    op.drop_column('reviews', 'review_request_at')
    # ### end Alembic commands ###
