"""add unique cal booking id

Revision ID: ca84f3dd5aea
Revises: 1250def90d1a
Create Date: 2026-09-29 00:06:23.561311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca84f3dd5aea'
down_revision: Union[str, Sequence[str], None] = '1250def90d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_appointments_cal_booking_id', 'appointments', ['cal_booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_appointments_cal_booking_id', 'appointments', type_='unique')
    # ### end Alembic commands ###
