"""add lead qualification fields

Revision ID: d99c966c1883
Revises: 15cb934546bc
Create Date: 2026-09-06 23:01:06.745009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99c966c1883'
down_revision: Union[str, Sequence[str], None] = '15cb934546bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('service_interest', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('urgency', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('budget', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('timeline', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'timeline')
    op.drop_column('leads', 'budget')
    op.drop_column('leads', 'urgency')
    op.drop_column('leads', 'service_interest')
    # ### end Alembic commands ###
